apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: node-list-binding
subjects:
  - kind: User
    name: arn:aws:iam::575108947352:root  # Your IAM user or role
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-list-role
  apiGroup: rbac.authorization.k8s.io
