# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: prft
#   labels:
#     app: prft
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: prft
#   template:
#     metadata:
#       labels:
#         app: prft
#     spec:
#       containers:
#         - name: prft
#           image: 274127640471.dkr.ecr.us-east-2.amazonaws.com/primuslearning:1.1
#           imagePullPolicy: Always
#           ports:
#             - containerPort: 8080
